# Generated by Django 5.1 on 2024-08-15 12:06

import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileimage',
            name='file_thumbnail_1440_960',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='images/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='fileimage',
            name='file_thumbnail_550_550',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='images/%Y/%m/%d/'),
        ),
    ]
